In [1]:
import numpy as np
import pandas as pd

In [2]:
ser = pd.Series(np.random.random(5), name = "Column 01")

In [3]:
ser

0    0.167439
1    0.473038
2    0.648196
3    0.630382
4    0.178150
Name: Column 01, dtype: float64

In [4]:
ser[2]

0.6481957897931904

In [5]:
from pandas_datareader import data as wb

In [6]:
PG = wb.DataReader('PG', data_source='yahoo', start='1995-1-1')

In [7]:
PG

                 Open       High        Low      Close    Volume  Adj Close
Date
1995-01-03  61.875000  62.500000  61.750000  62.375000   3318400   9.168104
1995-01-04  62.125000  62.625000  61.250000  61.875000   2218800   9.094613
1995-01-05  61.500000  61.750000  60.875000  61.000000   2319600   8.966002
1995-01-06  60.625000  61.625000  60.625000  61.125000   3438000   8.984375
1995-01-09  61.375000  61.625000  60.750000  60.875000   1795200   8.947629
1995-01-10  61.125000  61.750000  60.750000  61.625000   4364000   9.057867
1995-01-11  62.375000  62.375000  61.500000  61.500000   3738400   9.039494
1995-01-12  61.500000  62.125000  61.250000  62.125000   3307600   9.131359
1995-01-13  62.375000  63.375000  62.125000  62.500000   3992800   9.238525
1995-01-16  63.625000  63.875000  63.000000  63.000000   3677200   9.312433
1995-01-17  62.875000  63.250000  62.625000  63.250000   2437600   9.349388
1995-01-18  62.750000  63.000000  61.750000  61.875000   3535200   9.146140
1995-01-19  61.375000  61.625000  61.375000  61.625000   2491200   9.109186
1995-01-20  61.625000  61.625000  61.000000  61.375000   5130800   9.072232
1995-01-23  60.750000  62.000000  60.750000  62.000000   3147200   9.164617
1995-01-24  62.000000  62.125000  61.500000  61.875000   2016400   9.146140
1995-01-25  62.000000  63.125000  61.750000  62.750000   2802400   9.275479
1995-01-26  62.875000  63.375000  62.750000  63.000000   3124000   9.312433
1995-01-27  63.250000  65.000000  63.250000  64.750000   6247200   9.571112
1995-01-30  64.500000  66.250000  64.375000  65.750000   5226400   9.718929
1995-01-31  65.375000  66.000000  65.125000  65.125000   3934800   9.626543
1995-02-01  65.375000  65.375000  63.750000  63.875000   3047200   9.441773
1995-02-02  63.875000  64.500000  63.500000  64.375000   3810400   9.515681
1995-02-03  64.875000  65.500000  64.750000  65.000000   4442800   9.608066
1995-02-06  65.125000  66.500000  65.125000  66.500000   4003600   9.829791
1995-02-07  66.250000  66.375000  65.625000  66.375000   2380400   9.811314
1995-02-08  66.375000  66.375000  65.625000  65.625000   2481200   9.700452
1995-02-09  65.750000  65.875000  65.250000  65.500000   2143600   9.681975
1995-02-10  65.375000  65.625000  64.625000  65.375000   2445600   9.663497
1995-02-13  65.250000  65.875000  65.250000  65.875000   1726400   9.737406
...               ...        ...        ...        ...       ...        ...
2017-02-07  87.639999  88.279999  87.480003  88.010002   6646100  88.010002
2017-02-08  88.070000  88.339996  87.809998  88.330002   6815800  88.330002
2017-02-09  88.330002  88.779999  88.029999  88.669998   9914100  88.669998
2017-02-10  88.559998  88.730003  87.970001  87.970001  11057600  87.970001
2017-02-13  88.040001  88.360001  87.639999  88.309998   6905100  88.309998
2017-02-14  88.000000  88.220001  87.230003  87.860001  17199500  87.860001
2017-02-15  89.809998  91.150002  89.809998  91.120003  25770700  91.120003
2017-02-16  90.919998  91.120003  90.540001  90.790001  12404400  90.790001
2017-02-17  90.610001  91.360001  90.449997  91.089996  12084400  91.089996
2017-02-21  90.580002  91.800003  90.580002  91.669998   8160600  91.669998
2017-02-22  91.449997  91.800003  91.250000  91.440002   6742700  91.440002
2017-02-23  91.610001  91.800003  90.910004  91.129997   7574500  91.129997
2017-02-24  90.970001  91.339996  90.669998  91.050003   6600100  91.050003
2017-02-27  90.529999  90.910004  90.059998  90.889999  11640500  90.889999
2017-02-28  90.900002  91.790001  90.650002  91.070000  10470400  91.070000
2017-03-01  91.050003  91.889999  90.709999  91.660004   8747600  91.660004
2017-03-02  91.400002  91.589996  90.879997  90.910004   7026300  90.910004
2017-03-03  90.910004  90.910004  89.889999  90.500000   8334900  90.500000
2017-03-06  89.889999  90.510002  89.589996  90.370003   6462800  90.370003
2017-03-07  90.139999  90.489998  90.059998  90.290001   5236200  90.290001
2017-03-08  90.019997  90.349998  89.760002  90.139999   5503700  90.139999
2017-03-09  90.139999  90.489998  90.099998  90.339996   5587400  90.339996
2017-03-10  90.800003  91.160004  90.650002  91.070000   6733300  91.070000
2017-03-13  91.059998  91.489998  90.849998  91.309998   7073100  91.309998
2017-03-14  91.260002  91.589996  90.820000  91.000000   6684200  91.000000
2017-03-15  91.000000  91.779999  90.730003  91.400002   7713100  91.400002
2017-03-16  91.440002  91.720001  91.099998  91.440002   6572800  91.440002
2017-03-17  91.449997  92.000000  90.919998  91.000000  36378800  91.000000
2017-03-20  90.959999  91.410004  90.940002  91.220001   7504700  91.220001
2017-03-21  91.300003  91.750000  91.029999  91.190002   7885700  91.190002

[5594 rows x 6 columns]